
export const danceClasses = [
    {
      id: "hip-hop-101",
      name: "Hip Hop Fundamentals",
      studio: "Dance Hub Studio",
      location: "Surry Hills, Sydney",
      instructor: "Alex Johnson",
      price: 25.0,
      rating: 4.98,
      reviews: 132,
      capacity: "12 spots left",
      duration: "60 mins",
      level: "Beginner",
      nextClass: "Today at 6:00 PM",
      image: "/dance-flow-example-001.jpg",
    },
    {
      id: "ballet-basics",
      name: "Ballet Basics",
      studio: "Grace Movement",
      location: "Newtown, Sydney",
      instructor: "Sophie Lee",
      price: 30.0,
      rating: 4.92,
      reviews: 89,
      capacity: "8 spots left",
      duration: "75 mins",
      level: "Beginner",
      nextClass: "Tomorrow at 10:00 AM",
      image: "/dance-flow-example-002.jpg",
    },
    {
      id: "latin-energy",
      name: "Latin Fusion Energy",
      studio: "Salsa Syndicate",
      location: "Parramatta, Sydney",
      instructor: "Carlos Mendes",
      price: 28.0,
      rating: 4.87,
      reviews: 105,
      capacity: "5 spots left",
      duration: "60 mins",
      level: "Intermediate",
      nextClass: "Today at 7:30 PM",
      image: "/dance-flow-example-004.jpg",
    },
    {
      id: "jazz-blitz",
      name: "Jazz Dance Blitz",
      studio: "Urban Dance Co.",
      location: "Chatswood, Sydney",
      instructor: "Ella Cheng",
      price: 27.0,
      rating: 4.75,
      reviews: 78,
      capacity: "10 spots left",
      duration: "50 mins",
      level: "Beginner",
      nextClass: "Thursday at 5:30 PM",
      image: "/dance-flow-example-006.jpg",
    },
    {
      id: "contemporary-vibes",
      name: "Contemporary Vibes",
      studio: "The Movement Studio",
      location: "Glebe, Sydney",
      instructor: "Liam Park",
      price: 35.0,
      rating: 4.99,
      reviews: 146,
      capacity: "4 spots left",
      duration: "90 mins",
      level: "Advanced",
      nextClass: "Saturday at 11:00 AM",
      image: "/dance-flow-example-005.jpg",
    },
    {
      id: "street-style",
      name: "Street Style Choreo",
      studio: "Flow Factory",
      location: "Redfern, Sydney",
      instructor: "Nina Yang",
      price: 22.0,
      rating: 4.88,
      reviews: 110,
      capacity: "9 spots left",
      duration: "60 mins",
      level: "Intermediate",
      nextClass: "Friday at 6:30 PM",
      image: "/dance-flow-example-004.jpg",
    },
    {
      id: "salsa-spin",
      name: "Salsa Spin Mastery",
      studio: "Salsa Syndicate",
      location: "Parramatta, Sydney",
      instructor: "Diego Torres",
      price: 30.0,
      rating: 4.91,
      reviews: 98,
      capacity: "6 spots left",
      duration: "70 mins",
      level: "Intermediate",
      nextClass: "Tonight at 8:00 PM",
      image: "/dance-flow-example-001.jpg",
    },
    {
      id: "funk-flex",
      name: "Funk & Flex Moves",
      studio: "Flex Studios",
      location: "Bondi, Sydney",
      instructor: "Jade Lin",
      price: 26.0,
      rating: 4.85,
      reviews: 73,
      capacity: "11 spots left",
      duration: "55 mins",
      level: "All Levels",
      nextClass: "Sunday at 3:00 PM",
      image: "/dance-flow-0007-example-008.jpg",
    },
    {
      id: "twerk-technique",
      name: "Twerk Technique",
      studio: "Urban Motion",
      location: "Darlinghurst, Sydney",
      instructor: "Kiki Monroe",
      price: 24.0,
      rating: 4.67,
      reviews: 60,
      capacity: "7 spots left",
      duration: "60 mins",
      level: "Beginner",
      nextClass: "Today at 5:00 PM",
      image: "/dance-flow-0008-example-009.jpg",
    },
    {
      id: "breakdance-battle",
      name: "Breakdance Battle Prep",
      studio: "BreakPoint Studio",
      location: "Marrickville, Sydney",
      instructor: "Jay Rock",
      price: 32.0,
      rating: 4.95,
      reviews: 134,
      capacity: "3 spots left",
      duration: "80 mins",
      level: "Advanced",
      nextClass: "Wednesday at 6:00 PM",
      image: "/dance-flow-0009-example-010.jpg",
    },
    {
      id: "kpop-groove",
      name: "K-Pop Groove Session",
      studio: "Dance Seoul",
      location: "Strathfield, Sydney",
      instructor: "Minji Kim",
      price: 29.0,
      rating: 4.93,
      reviews: 122,
      capacity: "6 spots left",
      duration: "60 mins",
      level: "Beginner",
      nextClass: "Tuesday at 7:00 PM",
      image: "/dance-flow-0010-example-011.jpg",
    },
    {
      id: "house-steps",
      name: "House Dance Steps",
      studio: "Beat Studio",
      location: "Leichhardt, Sydney",
      instructor: "Oscar Diaz",
      price: 28.0,
      rating: 4.82,
      reviews: 91,
      capacity: "8 spots left",
      duration: "65 mins",
      level: "Intermediate",
      nextClass: "Friday at 7:30 PM",
      image: "/dance-flow-0011-example-012.jpg",
    },
    {
      id: "waacking-workout",
      name: "Waacking Workout",
      studio: "Groove House",
      location: "Haymarket, Sydney",
      instructor: "Lola Reyes",
      price: 26.0,
      rating: 4.76,
      reviews: 77,
      capacity: "5 spots left",
      duration: "60 mins",
      level: "All Levels",
      nextClass: "Monday at 6:00 PM",
      image: "/dance-flow-0012-example-013.jpg",
    },
    {
      id: "afrobeat-fever",
      name: "Afrobeat Fever",
      studio: "Rhythm Nation",
      location: "Liverpool, Sydney",
      instructor: "Kwame B.",
      price: 30.0,
      rating: 4.9,
      reviews: 113,
      capacity: "9 spots left",
      duration: "70 mins",
      level: "All Levels",
      nextClass: "Saturday at 2:00 PM",
      image: "/dance-flow-0013-example-014.jpg",
    },
    {
      id: "reggaeton-rhythm",
      name: "Reggaeton Rhythm Ride",
      studio: "Urban Motion",
      location: "Darlinghurst, Sydney",
      instructor: "Camila Rios",
      price: 27.0,
      rating: 4.86,
      reviews: 88,
      capacity: "10 spots left",
      duration: "60 mins",
      level: "Intermediate",
      nextClass: "Thursday at 7:00 PM",
      image: "/dance-flow-0014-example-015.jpg",
    },
  ];
  